sudo: false
services:
  - postgresql
addons:
  postgresql: "9.5"
env:
  global:
    - URL=http://localhost:8080
    - PORT=8080
    - NODE_ENV=development
    - SECRET=CODINGISGOOD
    - PG_URL=postgres://mcfrank16@127.0.0.1:5432/Epic_Mail_DB
    - PG_HOST=localhost
    - PG_USER=mcfrank
    - PG_DATABASE=Epic_Mail_DB
    - PG_PASSWORD=secret
    - PG_PORT=5432
language: node_js
node_js:
  - "10.4.0"
branches:
  only:
    - develop
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database Epic_Mail_DB;' -U postgres
  - psql -c "CREATE USER mcfrank WITH PASSWORD 'secret';" -U postgres
  - npm run db
script:
  - npm test
after_success:
  - codecov